### ISSUE TITLE
Headings inside <span>

### ISSUE THREAD

**Issue by jordanwillis** [travismbenton/Colmar_Academy#2]
I always recommend that everyone run their HTML through a validation service in order to make sure your final structure is valid and to also catch any typos or silly mistakes.  When I ran your project through the service, I noticed several instances where you wrapped headings or paragraphs (e.g. `<h1>`, `<h2>`, `<p>`, etc.) with a `<span>`.

https://github.com/travismbenton/Colmar_Academy/blob/5ffab2b231b8277da1c9593fe996ee21796ce7e1/index.html#L76-L78
https://github.com/travismbenton/Colmar_Academy/blob/5ffab2b231b8277da1c9593fe996ee21796ce7e1/index.html#L83-L85
etc.

It turns out that this is actually not something that is allowed and there is a better way to achieve the layout that you are after.  We can just let flexbox handle it for us.  To start out, we can create a structure like this to contain the image and text sections.  Notice also that it's best to just include the mobile image here as well and we can hide the other stuff later when in mobile mode.

``` html
<div class="content-image-box">
  <div class="media-container">
    <img class="desktop" src="resources/images/information-campus.jpg">
    <img class="mobile" src="resources/images/information-campus-mobile.jpg">
  </div>
  <div class="text-content">
    <h4>Our campus</h4>
    <p>Find which campus is close by you</p>
    <a href="#">Read more</a>
  </div>
</div>
```

In order to get these two containers to stack side by side like we want, we just need to make sure we configure `.content-image-box` as a flex container (e.g. `display: flex`).

``` css
.content-image-box {
  display: flex;
  padding: 1rem 0 1rem 1rem;
  border-bottom: 1px solid rgb(245, 245, 245);
}
```

Then we will control the width of the image by setting a width on the image's container element.

``` css
.content-image-box .media-container {
  width: 35%;
}
```

Next for all the text, we will again want to use a flex container, but this time with a `flex-direction` of `column` so that the text elements will stack on top of each other (along with a few other properties).

``` css
.content-image-box .text-content {
  display: flex;
  flex-direction: column;
  justify-content: center;
  width: 65%;
  padding: 0 0.75rem 0 1rem;
}
``` 

The end result is the side by side image/text with stacked text all without having to use a `<span>` or anything else like that.  Since we also included our mobile image here as well it will start out as hidden like this.

``` css
.content-image-box .mobile {
  display: none;
}
```

And then we can show the mobile image, hide the desktop, and switch our container to take up the full screen width like this.

``` css
@media only screen and (max-width: 895px) {
  .content-image-box .desktop {
    display: none;
  }

  .content-image-box .mobile {
    display: block;
  }

  .content-image-box {
    padding-left: 0;
    border-bottom: none;
  }

  .content-image-box .media-container {
    width: 100%;
  }
}
```
